{{- if .Values.flask.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "twotier.fullname" . }}
  labels:
    {{- include "twotier.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  minAvailable: {{ .Values.flask.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "twotier.flask.selectorLabels" . | nindent 6 }}
{{- end }}
