name: Security - Cosign Image Signing

permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_call:
    inputs:
      image-ref:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      image-ref:
        required: true
        default: "meshekar51/flask-app:latest"

jobs:
  sign-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.6.0"   # or a current supported release

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Sign image with Cosign (Keyless)
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign --yes "${{ inputs.image-ref }}"

      - name: Generate SBOM with Cosign
        run: |
          cosign generate sbom "${{ inputs.image-ref }}" --output-file sbom.json
