name: Security - Secrets Detection

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks
        # You may pin to the exact commit or the version.
        # uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
        uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
