name: Security - Secrets Detection

on:
  workflow_dispatch:

jobs:
  secrets:
    name: Detect Secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gitleaks/gitleaks-action@01599c76cf958b3c7db25f791872e165319ace00
        continue-on-error: true
